# -*- coding: utf-8 -*-
"""HackBioikadan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10uJLvXgYYbaVvbFBjns_jPDa9cghqnd5
"""

Name = "Ika Danjuma Mbateudi"
Email = "ikadanjuma@gmail.com"
Language = "python"
Biostack = "Drug development"
Slack_username = "@ikadan"
print('Ika Danjuma Mbateudi,', '@ikadan,', 'Python,' , 'ikadanjuma@gmail.com', 'Drugs development')
