# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuOnPAxdK8t5yuosbiulyExNhzypPcZE
"""

print('ejeh jemimah omaye,', '@omaye,', 'Python,' , 'jemimahomaye@gmail.com')